version: '3.5'

services:
  mariadb:
    build: './mariadb/'
    volumes:
      - flyweb-volume:/var/lib/mysql
    networks:
      - flyweb_network
    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flyweb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
  

  php:
    build: './php/'
    networks:
      - flyweb_network
    volumes:
      - ../pages/:/var/www/html/
      - ../components/:/var/www/html/components
      - ../js/:/var/www/html/js
      - ../img/:/var/www/html/img

  
  apache:
    build: './apache/'
    depends_on:
      - php
      - mariadb
    networks:
      - flyweb_network
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html/

volumes:
  flyweb-volume:
    driver: local

networks:
  flyweb_network:
    name: flyweb_network
